/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2022-05-27 22:20:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.Statement;
import com.user.*;
import java.sql.Connection;

public final class Admin_005fupdateMedicine_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.user");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Medico</title>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Encode+Sans+Expanded:400,600,700\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"plugin-frameworks/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"fonts/ionicons.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"common/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"demo.css\" />\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    $('#examples').DataTable( {\r\n");
      out.write("        \"pagingType\": \"full_numbers\"\r\n");
      out.write("   } );\r\n");
      out.write("} );\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"new/bootstrap.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"new/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"new/hi.css\" >\r\n");
      out.write(" <style>\r\n");
      out.write("\tbody {\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  background: url(https://images.pexels.com/photos/3850790/pexels-photo-3850790.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1);\r\n");
      out.write("  background-size: cover;\r\n");
      out.write("  font-family: sans-serif;\r\n");
      out.write("}\r\n");
      out.write(".box {\r\n");
      out.write(" /* position: absolute;*/\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  transform: translate(-12%, -5%);\r\n");
      out.write("  width: 92rem;\r\n");
      out.write("   padding: 2.5rem;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  background: rgba(0, 0, 0, 0.6);\r\n");
      out.write("  border-radius: 0.625rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box h2 {\r\n");
      out.write("  margin: 0 0 1.875rem;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".box .post_section h3 {\r\n");
      out.write("  color: white;\r\n");
      out.write("  font-weight: bold;}\r\n");
      out.write("  \r\n");
      out.write(" .box .post_section r {\r\n");
      out.write("  color: white;} \r\n");
      out.write("\r\n");
      out.write(".box .post_section a{\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 8px 16px;\r\n");
      out.write("  margin: 4px 2px;\r\n");
      out.write("  transition-duration: 0.4s;\r\n");
      out.write("  cursor: pointer;}\r\n");
      out.write("  \r\n");
      out.write(" .button1:hover {\r\n");
      out.write(" background-color: #E89481; \r\n");
      out.write(" color: black;\r\n");
      out.write("}\r\n");
      out.write(".wrapper .logo a{\r\n");
      out.write("color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper .nav q{\r\n");
      out.write("color: black;\r\n");
      out.write("}\r\n");
      out.write(" </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body background=\"https://images.pexels.com/photos/3850790/pexels-photo-3850790.jpeg?crop=entropy&cs=srgb&dl=pexels-ready-made-3850790.jpg&fit=crop&fm=jpg&h=1000&w=1300\">\r\n");

if(request.getParameter("Update")!=null)
{
out.println("<script>alert('Status Update Successfully...!')</script>");
}
else if(request.getParameter("stock")!=null)
{
out.println("<script>alert('Out of stock')</script>");
}
   
      out.write("\r\n");
      out.write("<!--  <header>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<a class=\"logo\" href=\"#\">Medico-One Step For Medicine</a>\r\n");
      out.write("<img src=\"images/brand.gif\"  style=\"width:60px;height:60px; transform: translate(-5%, 20%);\">\r\n");
      out.write("<a class=\"menu-nav-icon\" data-menu=\"#main-menu\" href=\"#\"><i class=\"ion-navicon\"></i></a>\r\n");
      out.write("<ul class=\"main-menu\" id=\"main-menu\">\r\n");
      out.write("<li><a href=\"AdminHome.jsp\" class=\"current\">Home</a></li>\r\n");
      out.write("<li><a href=\"UpdateMedicine.jsp\" >Add Medicine</a></li>\r\n");
      out.write("<li><a href=\"DistributeDataShow.jsp\" class=\"current-demo\">Distribute Data Show</a></li>\r\n");
      out.write("<li><a href=\"Admin_updateMedicine.jsp\" class=\"current-demo\">Update Medicine</a></li>\r\n");
      out.write("<li><a href=\"Admin_DistributePayBillDataShow.jsp\" class=\"current-demo\">Pay Bill Data Show</a></li>\r\n");
      out.write("<li><a href=\"LoginPage.jsp?logout\">Logout</a></li>\r\n");
      out.write("</ul> -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("                <div class=\"logo\">\r\n");
      out.write("                    <a href=\"#\">Medico: One stop for Medicines</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!--Nav Code-->\r\n");
      out.write("                <nav>\r\n");
      out.write("                    <a href=\"AdminHome.jsp\" class=\"current\"><q>Home</q></a>\r\n");
      out.write("                    <a href=\"UpdateMedicine.jsp\" ><q>Add Medicine</q></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"DistributeDataShow.jsp\" class=\"current-demo\"><q>Distributer Data</q></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"Admin_updateMedicine.jsp\" class=\"current-demo\"><q>Update Medicine</q></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"Admin_DistributePayBillDataShow.jsp\" class=\"current-demo\"><q>Payment</q></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"LoginPage.jsp?logout\"><q>Logout</q></a>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                </nav>\r\n");
      out.write("<div class=\"clearfix\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<section class=\"ptb-0\">\r\n");
      out.write("<div class=\"mb-30 brdr-ash-1 opacty-5\"></div>\r\n");
      out.write("<div class=\"container\" ><div class=\"box\">\r\n");
      out.write(" \t\t\t\t\t\r\n");
      out.write("\t\t<h2>Medicines Available</h2>\r\n");
      out.write("<div >\r\n");
      out.write(" <div  >\r\n");
      out.write("<div >\r\n");
      out.write("\r\n");
      out.write("<div  ><br>\r\n");
      out.write("<div class=\"post_section\">\r\n");
      out.write("<table align=\"center\" style=\"width: 100%;\" class=\"displays\" border=\"1\" cellpadding=\"10\" cellspacing=\"10\">\r\n");
      out.write("<tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<td><h3>Medicine_No</h3></td>\r\n");
      out.write("<td><h3>MedicineName:</h3></td>\r\n");
      out.write("<td><h3>CompanyName</h3></td>\r\n");
      out.write("<td><h3>DescriptionName</h3></td>\r\n");
      out.write("<td><h3>MFGDate</h3></td>\r\n");
      out.write("<td><h3>Price</h3></td>\r\n");
      out.write("<td><h3>Qty</h3></td>\r\n");
      out.write("<td><h3>ExpiryDate</h3></td>\r\n");
      out.write("<td><h3>Action</h3></td>\r\n");
      out.write("</tr>\r\n");

 try{
 int i=1;
 String query="select * from medicine_info";
 Connection conn=DBconn.conn();
 Statement stmt=conn.createStatement();
 ResultSet rs=stmt.executeQuery(query);
    while(rs.next()){
    {

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\r\n");
      out.write("<td><r>");
      out.print(rs.getString(9) );
      out.write("</r></td>\r\n");
      out.write("<td><r>");
      out.print(rs.getString(2) );
      out.write("</r></td>\r\n");
      out.write("\r\n");
      out.write("<td><r>");
      out.print(rs.getString(3) );
      out.write("</r></td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<td><r>");
      out.print(rs.getString(4) );
      out.write("</r></td>\r\n");
      out.write("\r\n");
      out.write("<td><r>");
      out.print(rs.getString(5) );
      out.write("</r></td>\r\n");
      out.write("\r\n");
      out.write("<td><r>");
      out.print(rs.getString(6) );
      out.write("</r></td>\r\n");
      out.write("<td><r>");
      out.print(rs.getString(8) );
      out.write("</r></td>\r\n");
      out.write("<td><r>");
      out.print(rs.getString(7) );
      out.write("</r></td>\r\n");
      out.write("\r\n");
      out.write("<td> <a href=\"AdminUpdateMedicine.jsp?id=");
      out.print(rs.getString(9));
      out.write(',');
      out.print(rs.getString(1));
      out.write("\" style=\"color: white;\"class=\"button1\">Update</a>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>  \r\n");
}
i++;
} 
      out.write('\r');
      out.write('\n');

}
catch (Exception e) {
e.printStackTrace();
}
      out.write("          \r\n");
      out.write("    </table>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</section><br><br><br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"plugin-frameworks/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<script src=\"plugin-frameworks/tether.min.js\"></script>\r\n");
      out.write("<script src=\"plugin-frameworks/bootstrap.js\"></script>\r\n");
      out.write("<script src=\"common/scripts.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
