/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2022-05-27 18:53:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class LoginPage_00201_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Blockchain</title>\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css?family=Encode+Sans+Expanded:400,600,700\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"plugin-frameworks/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"fonts/ionicons.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"common/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

	if(request.getParameter("logout")!=null)
	{
		session.invalidate();
		Thread.sleep(2000);
		out.println("<script>alert('Logout Successfully')</script>");
	}
	if(request.getParameter("Done")!=null)
	{
	out.println("<script>alert('Congratulations....Profle Added Successfully ...!')</script>");	
	}
	else if(request.getParameter("invalid")!=null)
	{
	out.println("<script>alert('Invalid Login Credential ...!')</script>");	
	}
	else if(request.getParameter("succ")!=null)
	{
	out.println("<script>alert('Congratulations....Register Successfuly...!')</script>");	
	}
   
      out.write("\r\n");
      out.write("\t<header>\t\t\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<a class=\"logo\" href=\"#\">Medicines Supply Chain using Block Chain</a>\r\n");
      out.write("\t\t\t<a class=\"menu-nav-icon\" data-menu=\"#main-menu\" href=\"#\"><i class=\"ion-navicon\"></i></a>\r\n");
      out.write("\t\t\t<ul class=\"main-menu\" id=\"main-menu\"><li><a href=\"RegisterPage.jsp\">REGISTER PAGE</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"LoginPage.jsp\" class=\"current\">LOGIN PAGE</a></li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"ptb-0\">\r\n");
      out.write("\t<div class=\"mb-30 brdr-ash-1 opacty-5\"></div>\r\n");
      out.write("\t\t<div class=\"container\"><br><br><br>\r\n");
      out.write("\t\t <div class=\"row\">\r\n");
      out.write("\t\t  <div class=\"col-sm-12 col-md-8\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<table align=\"center\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"img/admin.jpg\" width=\"10\" height=\"240\">\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\"><b>Login</b></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("            \t</table>\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t<form class=\"post_section\" action=\"AddLogin\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t<table align=\"center\" border=\"0\"  cellpadding=\"5\" cellspacing=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"2\"><div class=\"cleaner\" style=\"height: 20%\">&nbsp;&nbsp;&nbsp;&nbsp;</div></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Select Roll:</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><select style=\"width: 100%; height: 30px\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"username\" name=\"roll\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option selected=\"selected\">Select Roll</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"User\">User</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"Admin\">Admin</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"Distribute\">Distribute</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Email_ID:</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"email\" placeholder=\"mymail@mail.com\" required /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Password</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"password\" name=\"password\" placeholder=\"eg. X8df!90EO\" required /></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t     \t<td colspan=\"1\" align=\"center\"><input class=\"input-rounded-button\" type=\"submit\" value=\"LogIn\" style=\"height: 30px;width: 80px;\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t    \t\r\n");
      out.write("\t\t\t\t    \t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</form>\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-12 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<img src=\"images/M3.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section><br><br><br><br><br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t<footer class=\"bg-191 color-ccc\">\r\n");
      out.write("\t\t\t<div class=\"brdr-ash-1 opacty-2\"></div>\r\n");
      out.write("\t\t\t<div class=\"oflow-hidden color-ash font-9 text-sm-center ptb-sm-5\"><br>\r\n");
      out.write("\t\t\t<p class=\"color-ash\">\r\n");
      out.write("\t\t\t\tCopyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class=\"ion-heart\" aria-hidden=\"true\"></i> by <a href=\"#\" target=\"_blank\">Digital Certificate on Blockchain</a>\r\n");
      out.write("\t\t\t</p><br>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<script src=\"plugin-frameworks/jquery-3.2.1.min.js\"></script>\t\r\n");
      out.write("\t<script src=\"plugin-frameworks/tether.min.js\"></script>\t\r\n");
      out.write("\t<script src=\"plugin-frameworks/bootstrap.js\"></script>\t\r\n");
      out.write("\t<script src=\"common/scripts.js\"></script>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
